/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Rescue.Operator;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OperatorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OperatorWorkRequest;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class OperatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OperatorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private OperatorOrganization organization;
    private EcoSystem business;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    public OperatorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, OperatorOrganization organization, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.business = business;
        this.userAccount = account;
        popSeverity();
        popRegion();
        populateComboBox();
    }
    
       private void populateComboBox() {
        networkJComboBox.removeAllItems();
        
        for (Network network : business.getNetworkList()) {
            networkJComboBox.addItem(network);
        }

    }
       
       private void popRegion(){
            regionJComboBox1.removeAllItems();
            regionJComboBox1.addItem("NORTH");
            regionJComboBox1.addItem("SOUTH");
            regionJComboBox1.addItem("EAST");
            regionJComboBox1.addItem("WEST");

        }
       
       private void popSeverity(){
            severityJComboBox.removeAllItems();
            severityJComboBox.addItem("Mild");
            severityJComboBox.addItem("Moderate");
            severityJComboBox.addItem("Extreme");


        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        regionJComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        severityJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        reporterNameTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        messageTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Operator");
        add(jLabel1);
        jLabel1.setBounds(470, 220, 163, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Network:");
        add(jLabel2);
        jLabel2.setBounds(540, 290, 85, 22);

        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox);
        networkJComboBox.setBounds(630, 290, 146, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Region:");
        add(jLabel3);
        jLabel3.setBounds(550, 340, 70, 22);

        add(regionJComboBox1);
        regionJComboBox1.setBounds(630, 340, 146, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description:");
        add(jLabel4);
        jLabel4.setBounds(510, 380, 110, 22);
        add(descriptionTextField);
        descriptionTextField.setBounds(630, 380, 282, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Severity:");
        add(jLabel5);
        jLabel5.setBounds(540, 430, 80, 22);

        add(severityJComboBox);
        severityJComboBox.setBounds(630, 430, 143, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address of activity:");
        add(jLabel6);
        jLabel6.setBounds(460, 480, 171, 22);

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });
        add(addressTextField);
        addressTextField.setBounds(630, 480, 282, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reportees name:");
        add(jLabel7);
        jLabel7.setBounds(470, 530, 155, 22);
        add(reporterNameTextField);
        reporterNameTextField.setBounds(630, 530, 144, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Create Alert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(1090, 760, 170, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Mail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1280, 760, 80, 31);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Create Alert:");
        add(jLabel8);
        jLabel8.setBounds(970, 640, 231, 44);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Message:");
        add(jLabel10);
        jLabel10.setBounds(1040, 700, 85, 22);
        add(messageTxt);
        messageTxt.setBounds(1140, 700, 282, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Rescue/Operator/rescueImage.JPG"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1950, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if((!descriptionTextField.getText().equals("")) || (!addressTextField.getText().equals("")) || (!reporterNameTextField.getText().equals(""))){
        Network network = (Network)networkJComboBox.getSelectedItem();
        String region = (String)regionJComboBox1.getSelectedItem();
        String description = descriptionTextField.getText();
        String severity = (String)severityJComboBox.getSelectedItem();
        String address = addressTextField.getText();
        String reporterName=reporterNameTextField.getText();
        String alert = description+" of "+severity+" severity " +network+" : "+region;
        OperatorWorkRequest request= new OperatorWorkRequest(network,region,description,severity,address,reporterName,alert);
            System.out.println(alert);
        //organization.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        business.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(this, "Alert created!!!");
        }else{
             JOptionPane.showMessageDialog(null, "Enter value for all fields", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
//        String network = (String)networkJComboBox.getSelectedItem();
//        if(network.equalsIgnoreCase("boston")){
//            String to_add = "nidhi3srinivas@gmail.com";
//        }else if(network.equalsIgnoreCase("newyork")){
//            String to_add = "vishnu.vizz@gmail.com";
//        }else if(network.equalsIgnoreCase("chicago")){
//            String to_add = "inchara1710@gmail.com";
        
        String description = messageTxt.getText();
        String to_add = "vishnu.vizz@gmail.com,inchara1710@gmail.com,nidhi3srinivas@gmail.com";
        
        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.socketFactory.port", "587");
        prop.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        prop.put("mail.smtp.auth","true");
        prop.put("mail.smtp.port","587");
        
        Session session = Session.getDefaultInstance(prop,
            new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication("eros.alerts.neu@gmail.com", "eros12345");
                }
                }
                
                );
        
        try{
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("eros.alerts.neu@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to_add));
            message.setSubject("EROS ALERTS");
            message.setText(description);
            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Message sent..");
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField messageTxt;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JComboBox regionJComboBox1;
    private javax.swing.JTextField reporterNameTextField;
    private javax.swing.JComboBox severityJComboBox;
    // End of variables declaration//GEN-END:variables
}
