/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Medical.Patient;

import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.Patient.Gender;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.Medical.Nurse.NurseWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
  
    public PatientWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        System.out.println("Organisation: "+organization.getName());
        
        stateComboBox();;
        cityComboBox();
        genderComboBox();
        
    }
    
    public void stateComboBox(){
        statejComboBox.removeAllItems();
        statejComboBox.addItem("Massachusetts");
        statejComboBox.addItem("NewYork");
        statejComboBox.addItem("Texas");
    }
    
    public void cityComboBox(){
        cityjComboBox.removeAllItems();
        cityjComboBox.addItem("Boston");
        cityjComboBox.addItem("NewYork");
        cityjComboBox.addItem("Rochester");
        cityjComboBox.addItem("Dallas");
        cityjComboBox.addItem("Austin");
    }
    
    public void genderComboBox(){
        genderjComboBox.removeAllItems();;
        for(Patient.Gender g: Patient.Gender.values()){
            genderjComboBox.addItem(g);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        genderjComboBox = new javax.swing.JComboBox();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saveDetailsjButton = new javax.swing.JButton();
        statejComboBox = new javax.swing.JComboBox();
        cityjComboBox = new javax.swing.JComboBox();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Patient Information:");
        add(jLabel1);
        jLabel1.setBounds(660, 190, 241, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personal Details:");
        add(jLabel2);
        jLabel2.setBounds(660, 240, 153, 22);

        genderjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderjComboBoxActionPerformed(evt);
            }
        });
        add(genderjComboBox);
        genderjComboBox.setBounds(720, 460, 159, 22);
        add(txtMobile);
        txtMobile.setBounds(720, 410, 159, 22);
        add(txtEmail);
        txtEmail.setBounds(720, 370, 159, 22);
        add(txtAge);
        txtAge.setBounds(720, 330, 159, 22);
        add(txtName);
        txtName.setBounds(720, 290, 159, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address:");
        add(jLabel3);
        jLabel3.setBounds(1140, 310, 78, 22);

        saveDetailsjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveDetailsjButton.setText("Save");
        saveDetailsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDetailsjButtonActionPerformed(evt);
            }
        });
        add(saveDetailsjButton);
        saveDetailsjButton.setBounds(720, 500, 446, 33);

        add(statejComboBox);
        statejComboBox.setBounds(1200, 340, 140, 22);

        add(cityjComboBox);
        cityjComboBox.setBounds(1200, 380, 140, 22);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(720, 550, 107, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sender");
        add(jLabel7);
        jLabel7.setBounds(650, 460, 64, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City");
        add(jLabel8);
        jLabel8.setBounds(1150, 380, 34, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Age");
        add(jLabel9);
        jLabel9.setBounds(660, 330, 34, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        add(jLabel10);
        jLabel10.setBounds(660, 370, 49, 22);

        jLabel11.setText("jLabel7");
        add(jLabel11);
        jLabel11.setBounds(660, 370, 41, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile");
        add(jLabel12);
        jLabel12.setBounds(649, 410, 70, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Name");
        add(jLabel18);
        jLabel18.setBounds(660, 290, 53, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("State");
        add(jLabel19);
        jLabel19.setBounds(1140, 340, 47, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Medical/Patient/Medical.JPG"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(0, 0, 1950, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        NurseWorkAreaJPanel nwjp = (NurseWorkAreaJPanel) component;
        nwjp.patientComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveDetailsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDetailsjButtonActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText();
        int age = Integer.parseInt(txtAge.getText());
        String mail = txtEmail.getText();
        int mobile = Integer.parseInt(txtMobile.getText());
        String state = (String) statejComboBox.getSelectedItem();
        String city = (String) cityjComboBox.getSelectedItem();
        Gender gender = (Gender) genderjComboBox.getSelectedItem();
        Patient patient = new Patient(name,age,mobile,mail,gender,state,city);
        PatientDirectory pd = organization.getPatientDirectory();
        pd.getPatientDirectory().add(patient);
        organization.setPatientDirectory(pd);
        JOptionPane.showMessageDialog(this, "Patient details saved successfully");
        
        
        //organization.getPatientDirectory().getPatientDirectory().add(patient);
    }//GEN-LAST:event_saveDetailsjButtonActionPerformed

    private void genderjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox cityjComboBox;
    private javax.swing.JComboBox genderjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton saveDetailsjButton;
    private javax.swing.JComboBox statejComboBox;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
