/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.VolunteerAdminOrganization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.Volunteer.Volunteer.VolunteerListJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class VolunteerAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private VolunteerAdminOrganization organization;
    private VolunteerOrganization volOrg;
    private Enterprise enterprise;
    private EcoSystem system;

    public VolunteerAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, VolunteerAdminOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        if (enterprise.getOrganizationDirectory().getOrganizationList().size() > 0) {
            this.volOrg = (VolunteerOrganization) enterprise.getOrganizationDirectory().getOrganizationList().get(0);
        }
        System.out.println("volorg = " + this.volOrg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEmployeejButton = new javax.swing.JButton();
        manageUserjButton = new javax.swing.JButton();
        manageOrganisationjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        manageEmployeejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageEmployeejButton.setText("Manage Employee");
        manageEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeejButtonActionPerformed(evt);
            }
        });
        add(manageEmployeejButton);
        manageEmployeejButton.setBounds(550, 370, 390, 40);

        manageUserjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageUserjButton.setText("Manage User Account");
        manageUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserjButtonActionPerformed(evt);
            }
        });
        add(manageUserjButton);
        manageUserjButton.setBounds(550, 431, 390, 40);

        manageOrganisationjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageOrganisationjButton.setText("Manage Organisation");
        manageOrganisationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganisationjButtonActionPerformed(evt);
            }
        });
        add(manageOrganisationjButton);
        manageOrganisationjButton.setBounds(550, 311, 390, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Volunteer Admin Work Area");
        add(jLabel1);
        jLabel1.setBounds(260, 79, 680, 60);

        btnList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnList.setText("Volunteer List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });
        add(btnList);
        btnList.setBounds(550, 501, 390, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(1190, 550, 770, 450);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel3.setText("jLabel2");
        add(jLabel3);
        jLabel3.setBounds(0, 550, 600, 450);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel4.setText("jLabel2");
        add(jLabel4);
        jLabel4.setBounds(600, 550, 600, 450);

        jLabel5.setText("jLabel2");
        add(jLabel5);
        jLabel5.setBounds(600, 700, 590, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeejButtonActionPerformed
        // TODO add your handling code here:
        VolunteerManageEmployeeJPanel manageEmployeeJPanel = new VolunteerManageEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("VolunteerManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeejButtonActionPerformed

    private void manageUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserjButtonActionPerformed
        // TODO add your handling code here:
        VolunteerManageUserAccountJPanel muajp = new VolunteerManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("VolunteerManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserjButtonActionPerformed

    private void manageOrganisationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganisationjButtonActionPerformed
        // TODO add your handling code here:
        VolunteerManageOrganisationJPanel manageOrganizationJPanel = new VolunteerManageOrganisationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("VolunteerManageOrganisationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganisationjButtonActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:

        System.out.println("calling vl" + organization);
        VolunteerListJPanel vljp = new VolunteerListJPanel(userProcessContainer, account, volOrg, enterprise);
        userProcessContainer.add("VolunteerListJPanel", vljp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manageEmployeejButton;
    private javax.swing.JButton manageOrganisationjButton;
    private javax.swing.JButton manageUserjButton;
    // End of variables declaration//GEN-END:variables
}
