/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Medical.Nurse;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignWorkRequest;
import Business.WorkQueue.PatientStatusWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Medical.Patient.PatientWorkAreaJPanel;
import UserInterface.Medical.Patient.SearchPatientJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vishnu
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private NurseOrganization organization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Patient p;
    private PatientDirectory pd;

    public NurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, NurseOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = (NurseOrganization) organization;
        this.enterprise = enterprise;
        this.system = system;
        labelNurse.setText(userAccount.getEmployee().getName());
        patientComboBox();
        doctorComboBox();
        patientStatus();
    }

    public void patientComboBox() {
        patientjComboBox.removeAllItems();
        for (Patient p : organization.getPatientDirectory().getPatientDirectory()) {
            patientjComboBox.addItem(p);
        }
    }

    public void doctorComboBox() {
        doctorjComboBox.removeAllItems();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DoctorOrganization) {
                for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                    doctorjComboBox.addItem(ua);
                }
            }
        }
    }

    public void patientStatus() {
        DefaultTableModel dtm = (DefaultTableModel) statusjTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[2] = request.getStatus();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        doctorjComboBox = new javax.swing.JComboBox();
        assignDoctorjButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        weightjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BPjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        temperaturejTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sendReportjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusjTable = new javax.swing.JTable();
        processjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelNurse = new javax.swing.JLabel();
        patientDetailsBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtInjury = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NurseWorkArea");
        add(jLabel1);
        jLabel1.setBounds(66, 13, 145, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient:");
        add(jLabel2);
        jLabel2.setBounds(424, 300, 110, 22);

        patientjComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientjComboBoxActionPerformed(evt);
            }
        });
        add(patientjComboBox);
        patientjComboBox.setBounds(550, 300, 139, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor:");
        add(jLabel3);
        jLabel3.setBounds(422, 340, 110, 22);

        doctorjComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(doctorjComboBox);
        doctorjComboBox.setBounds(550, 340, 141, 22);

        assignDoctorjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assignDoctorjButton.setText("Assign Doctor");
        assignDoctorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDoctorjButtonActionPerformed(evt);
            }
        });
        add(assignDoctorjButton);
        assignDoctorjButton.setBounds(710, 300, 200, 62);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight:");
        add(jLabel7);
        jLabel7.setBounds(475, 640, 110, 22);

        weightjTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(weightjTextField);
        weightjTextField.setBounds(650, 640, 110, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Pressure:");
        add(jLabel5);
        jLabel5.setBounds(470, 560, 160, 22);

        BPjTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(BPjTextField);
        BPjTextField.setBounds(650, 560, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Temperatue:");
        add(jLabel6);
        jLabel6.setBounds(475, 600, 140, 22);

        temperaturejTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(temperaturejTextField);
        temperaturejTextField.setBounds(650, 600, 110, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient Report:");
        add(jLabel9);
        jLabel9.setBounds(490, 390, 138, 22);

        sendReportjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sendReportjButton.setText("Send Report");
        sendReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReportjButtonActionPerformed(evt);
            }
        });
        add(sendReportjButton);
        sendReportjButton.setBounds(610, 730, 190, 37);

        statusjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor", "Nurse", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statusjTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(550, 420, 358, 77);

        processjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        processjButton.setText("Process");
        processjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processjButtonActionPerformed(evt);
            }
        });
        add(processjButton);
        processjButton.setBounds(550, 510, 358, 34);

        jLabel4.setText("Nurse:");
        add(jLabel4);
        jLabel4.setBounds(66, 47, 38, 16);

        labelNurse.setText("NurseName");
        add(labelNurse);
        labelNurse.setBounds(116, 47, 66, 16);

        patientDetailsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientDetailsBtn.setText("Enter Patient Details");
        patientDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDetailsBtnActionPerformed(evt);
            }
        });
        add(patientDetailsBtn);
        patientDetailsBtn.setBounds(550, 230, 358, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Injury:");
        add(jLabel8);
        jLabel8.setBounds(478, 680, 100, 22);

        txtInjury.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(txtInjury);
        txtInjury.setBounds(650, 680, 110, 22);

        searchjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });
        add(searchjButton);
        searchjButton.setBounds(613, 790, 190, 37);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Medical/Nurse/Medical.JPG"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10);
        jLabel10.setBounds(0, 0, 1950, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void patientDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDetailsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("PatientWorkAreaJPanel", new PatientWorkAreaJPanel(userProcessContainer, userAccount, organization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_patientDetailsBtnActionPerformed

    private void patientjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientjComboBoxActionPerformed

    private void assignDoctorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDoctorjButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("useraccount = " + userAccount);
        Patient selectedPatent = (Patient) patientjComboBox.getSelectedItem();
        UserAccount selectedDoctor = (UserAccount) doctorjComboBox.getSelectedItem();
        AssignWorkRequest awr = new AssignWorkRequest();
        awr.setPatient(selectedPatent);
        awr.setSender(userAccount);
        awr.setReceiver(selectedDoctor);
        System.out.println("Selected Doctor: " + selectedDoctor);

        selectedDoctor.getWorkQueue().getWorkRequestList().add(awr);
        JOptionPane.showMessageDialog(null, "Assigned successfully");
    }//GEN-LAST:event_assignDoctorjButtonActionPerformed

    private void processjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = statusjTable.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) statusjTable.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");

            } else {
                request.setReceiver(userAccount);
                request.setStatus("Processing");
                patientStatus();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");

        }
    }//GEN-LAST:event_processjButtonActionPerformed

    private void sendReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReportjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = statusjTable.getSelectedRow();

        if (selectedRow >= 0) {
            PatientStatusWorkRequest pswr = (PatientStatusWorkRequest) statusjTable.getValueAt(selectedRow, 0);
            pswr.setReceiver(userAccount);
            pswr.setStatus("Completed");
            pswr.setBloodPressure(Float.parseFloat(BPjTextField.getText()));
            pswr.setTemperature(Float.parseFloat(temperaturejTextField.getText()));
            pswr.setWeight(Float.parseFloat(weightjTextField.getText()));
            pswr.setInjury(txtInjury.getText());

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof DoctorOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(pswr);
                userAccount.getWorkQueue().getWorkRequestList().add(pswr);
            }

            JOptionPane.showMessageDialog(this, "Patient report sent successfully!!");
        }
    }//GEN-LAST:event_sendReportjButtonActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("SearchPatientWorkAreaJPanel", new SearchPatientJPanel(userProcessContainer, userAccount, organization));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_searchjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPjTextField;
    private javax.swing.JButton assignDoctorjButton;
    private javax.swing.JComboBox doctorjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNurse;
    private javax.swing.JButton patientDetailsBtn;
    private javax.swing.JComboBox patientjComboBox;
    private javax.swing.JButton processjButton;
    private javax.swing.JButton searchjButton;
    private javax.swing.JButton sendReportjButton;
    private javax.swing.JTable statusjTable;
    private javax.swing.JTextField temperaturejTextField;
    private javax.swing.JTextField txtInjury;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
