/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Rescue.GroundSquad;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Network.Person;
import Business.Organization.ChiefOrganization;
import Business.Organization.GroundSquadOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.InfoWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vishnu
 */
public class GroundSquadWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private GroundSquadOrganization organization;
    private Enterprise enterprise;
    private Network network;
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public GroundSquadWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, GroundSquadOrganization organization,Enterprise enterprise, EcoSystem business) {
        
        
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.business = business;
        this.organization = (GroundSquadOrganization) organization;
        
        for(Network n : business.getNetworkList()) {
            
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
               this.network = n;
                if(e.equals(enterprise)) {
                
                    System.out.println("Network: "+network);
                    break;
                }
            }
        }
//        Network n = new Network();
//        n.setName("Network1");
//        this.network = n;
        
        populateTable();
      //  popPerson();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[2] = request.getStatus();

            model.addRow(row);
        }
    }
    
//    public void popPerson(){
//        DefaultTableModel model = (DefaultTableModel) personjTable.getModel();
//        model.setRowCount(0);
//        
//        if(network == null) {
//            System.out.println("network is null");
//        }
//        if(network.getPersonDirectory() == null) {
//            System.out.println("network.getPersonDirectory() is null");
//            System.out.println(network);
//        }
////        if(network.getPersonDirectory().getPersonDirectory().equals(null)) {
////            System.out.println("network.getPersonDirectory().getPersonDirectory() is null");
////        }
//        for(Person p : network.getPersonDirectory().getPersonDirectory()) {
//            Object[] row = new Object[5];
//            row[0] = p;
//            row[1] = p.getAge();
//            row[2] = p.getGender();
//            row[3] = p.getMobileNo();
//            row[4] = p.getEmail();
//
//            model.addRow(row);
//        }
//
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaSafetybuttonGroup = new javax.swing.ButtonGroup();
        backupbuttonGroup = new javax.swing.ButtonGroup();
        assignJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPeopleSaved = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPeopleDead = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbtnAreaYes = new javax.swing.JRadioButton();
        rbtnAreaNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbtnBackupYes = new javax.swing.JRadioButton();
        rbtnBackupNo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActivityDesc = new javax.swing.JTextArea();
        btnInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        assignJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        assignJButton.setText("Process");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton);
        assignJButton.setBounds(570, 320, 452, 38);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ground Squad");
        add(jLabel1);
        jLabel1.setBounds(540, 180, 320, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("People saved:");
        add(jLabel2);
        jLabel2.setBounds(1010, 600, 160, 27);
        add(txtPeopleSaved);
        txtPeopleSaved.setBounds(1220, 590, 84, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("People dead:");
        add(jLabel3);
        jLabel3.setBounds(1010, 630, 150, 31);
        add(txtPeopleDead);
        txtPeopleDead.setBounds(1220, 630, 197, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Area Safe?");
        add(jLabel4);
        jLabel4.setBounds(1010, 670, 140, 22);

        areaSafetybuttonGroup.add(rbtnAreaYes);
        rbtnAreaYes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnAreaYes.setForeground(new java.awt.Color(255, 0, 0));
        rbtnAreaYes.setText("Yes");
        add(rbtnAreaYes);
        rbtnAreaYes.setBounds(1220, 670, 61, 31);

        areaSafetybuttonGroup.add(rbtnAreaNo);
        rbtnAreaNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnAreaNo.setForeground(new java.awt.Color(255, 0, 0));
        rbtnAreaNo.setText("No");
        rbtnAreaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAreaNoActionPerformed(evt);
            }
        });
        add(rbtnAreaNo);
        rbtnAreaNo.setBounds(1300, 670, 53, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Need backup?");
        add(jLabel5);
        jLabel5.setBounds(1010, 720, 160, 22);

        backupbuttonGroup.add(rbtnBackupYes);
        rbtnBackupYes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnBackupYes.setForeground(new java.awt.Color(255, 0, 0));
        rbtnBackupYes.setText("Yes");
        add(rbtnBackupYes);
        rbtnBackupYes.setBounds(1220, 710, 61, 31);

        backupbuttonGroup.add(rbtnBackupNo);
        rbtnBackupNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnBackupNo.setForeground(new java.awt.Color(255, 0, 0));
        rbtnBackupNo.setText("No");
        add(rbtnBackupNo);
        rbtnBackupNo.setBounds(1300, 710, 53, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Activity description:");
        add(jLabel6);
        jLabel6.setBounds(1010, 760, 190, 22);

        txtActivityDesc.setColumns(20);
        txtActivityDesc.setRows(5);
        jScrollPane2.setViewportView(txtActivityDesc);

        add(jScrollPane2);
        jScrollPane2.setBounds(1220, 750, 197, 54);

        btnInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInfo.setText("Send Information");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        add(btnInfo);
        btnInfo.setBounds(1220, 810, 197, 38);

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(570, 230, 452, 76);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Incident Details:");
        add(jLabel7);
        jLabel7.setBounds(1070, 540, 340, 44);
        add(jSeparator1);
        jSeparator1.setBounds(680, 390, 787, 10);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Rescue/GroundSquad/rescueImage.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");
        add(jLabel8);
        jLabel8.setBounds(0, 0, 1950, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                
            }else {
                request.setReceiver(userAccount);
                request.setStatus("Processing");
                populateTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
            
        }


    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow >= 0) {
            InfoWorkRequest iwr = (InfoWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
        
            iwr.setReceiver(userAccount);
            iwr.setStatus("Completed");
            iwr.setSavedPeople(Integer.parseInt(txtPeopleSaved.getText()));
            iwr.setDeadPeople(Integer.parseInt(txtPeopleDead.getText()));
            if (rbtnAreaYes.isSelected()){
                iwr.setAreaSafe("Area is safe");
            }else{
                iwr.setAreaSafe("Area unsafe!!");
            }

            if (rbtnBackupYes.isSelected()){
                iwr.setBackup("Need backup");
            }else{
                iwr.setBackup("No backup needed");
            }

            iwr.setDescActivity(txtActivityDesc.getText());
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ChiefOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(iwr);
            userAccount.getWorkQueue().getWorkRequestList().add(iwr);
        }
        

        JOptionPane.showMessageDialog(this,"Information sent to Chief successfully");
        
        }
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void rbtnAreaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAreaNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAreaNoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup areaSafetybuttonGroup;
    private javax.swing.JButton assignJButton;
    private javax.swing.ButtonGroup backupbuttonGroup;
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtnAreaNo;
    private javax.swing.JRadioButton rbtnAreaYes;
    private javax.swing.JRadioButton rbtnBackupNo;
    private javax.swing.JRadioButton rbtnBackupYes;
    private javax.swing.JTextArea txtActivityDesc;
    private javax.swing.JTextField txtPeopleDead;
    private javax.swing.JTextField txtPeopleSaved;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
