/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Medical;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.MedicalAdminOrganization;
import Business.Organization.RescueAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class MedicalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account; 
    MedicalAdminOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;
    public MedicalAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, MedicalAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.business=business;
        this.organization= organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEmployeejButton = new javax.swing.JButton();
        manageUserjButton = new javax.swing.JButton();
        manageOrganisationjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        manageEmployeejButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageEmployeejButton.setText("Manage Employee");
        manageEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeejButtonActionPerformed(evt);
            }
        });
        add(manageEmployeejButton);
        manageEmployeejButton.setBounds(560, 270, 340, 50);

        manageUserjButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageUserjButton.setText("Manage User Account");
        manageUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserjButtonActionPerformed(evt);
            }
        });
        add(manageUserjButton);
        manageUserjButton.setBounds(560, 340, 340, 50);

        manageOrganisationjButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        manageOrganisationjButton.setText("Manage Organisation");
        manageOrganisationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganisationjButtonActionPerformed(evt);
            }
        });
        add(manageOrganisationjButton);
        manageOrganisationjButton.setBounds(557, 200, 340, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MEDICAL ADMIN WORK AREA");
        add(jLabel1);
        jLabel1.setBounds(370, 40, 480, 70);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Medical/Medical.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeejButtonActionPerformed
        // TODO add your handling code here:
        MedicalManageEmployeeJPanel manageEmployeeJPanel = new MedicalManageEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("MedicalManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeejButtonActionPerformed

    private void manageUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserjButtonActionPerformed
        // TODO add your handling code here:
        MedicalManageUserAccountJPanel muajp = new MedicalManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("MedicalManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserjButtonActionPerformed

    private void manageOrganisationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganisationjButtonActionPerformed
        // TODO add your handling code here:
        MedicalManageOrganisationJPanel manageOrganizationJPanel = new MedicalManageOrganisationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("MedicalManageOrganisationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganisationjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEmployeejButton;
    private javax.swing.JButton manageOrganisationjButton;
    private javax.swing.JButton manageUserjButton;
    // End of variables declaration//GEN-END:variables
}
