/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer.Volunteer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import Business.Volunteer.BloodDonations;
import Business.Volunteer.BloodDonations.BloodType;
import Business.Volunteer.CashDonations;
import Business.Volunteer.ClothDonations;
import Business.Volunteer.Volunteer;
import Business.WorkQueue.MoneyContributionWorkRequest;
import Business.WorkQueue.QuantityBloodWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Validator;

/**
 *
 * @author Vishnu
 */
public class VolunteerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Volunteer volunteer;

    public VolunteerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, VolunteerOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        labelVolunteer1.setText(account.getEmployee().getName());

//        totalBlood();
//        totalMoney();
        bloodGroup();
        quantity();

    }

    public void bloodGroup() {
        bloodGroupComboBox.removeAllItems();
        for (BloodDonations.BloodType bd : BloodDonations.BloodType.values()) {
            bloodGroupComboBox.addItem(bd);
        }
    }

    double i = 0;

    public void quantity() {
        quantityComboBox.removeAllItems();
        quantityComboBox.addItem(i + 0.5);
        quantityComboBox.addItem(i + 1);
        quantityComboBox.addItem(i + 1.5);

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelVolunteer = new javax.swing.JLabel();
        btnBlood = new javax.swing.JButton();
        btnClothes = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bloodGroupComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        quantityComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        clothesjCheckBox = new javax.swing.JCheckBox();
        comfortersjCheckBox = new javax.swing.JCheckBox();
        sweatersjCheckBox = new javax.swing.JCheckBox();
        shoesjCheckBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox200 = new javax.swing.JCheckBox();
        jCheckBox500 = new javax.swing.JCheckBox();
        jCheckBox1000 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtCause = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtQuantityCloth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelVolunteer1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("VolunteerWorkArea");
        add(jLabel1);
        jLabel1.setBounds(310, 22, 410, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Volunteer name:");
        add(jLabel2);
        jLabel2.setBounds(746, 80, 180, 22);

        labelVolunteer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(labelVolunteer);
        labelVolunteer.setBounds(900, 80, 170, 0);

        btnBlood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBlood.setText("Donate Blood");
        btnBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodActionPerformed(evt);
            }
        });
        add(btnBlood);
        btnBlood.setBounds(690, 510, 240, 37);

        btnClothes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClothes.setText("Donate Clothes");
        btnClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesActionPerformed(evt);
            }
        });
        add(btnClothes);
        btnClothes.setBounds(972, 510, 220, 37);

        btnMoney.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoney.setText("Donate Money");
        btnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyActionPerformed(evt);
            }
        });
        add(btnMoney);
        btnMoney.setBounds(1240, 510, 220, 37);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Blood group:");
        add(jLabel6);
        jLabel6.setBounds(720, 270, 120, 22);

        bloodGroupComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(bloodGroupComboBox);
        bloodGroupComboBox.setBounds(840, 270, 160, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Quantity:");
        add(jLabel3);
        jLabel3.setBounds(752, 310, 90, 22);

        quantityComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(quantityComboBox);
        quantityComboBox.setBounds(840, 310, 160, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Donate Blood:");
        add(jLabel7);
        jLabel7.setBounds(750, 240, 160, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Donate Clothes:");
        add(jLabel8);
        jLabel8.setBounds(1001, 240, 170, 22);

        clothesjCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clothesjCheckBox.setText("Clothes");
        add(clothesjCheckBox);
        clothesjCheckBox.setBounds(1001, 270, 150, 31);

        comfortersjCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comfortersjCheckBox.setText("Comforters");
        add(comfortersjCheckBox);
        comfortersjCheckBox.setBounds(1003, 310, 170, 31);

        sweatersjCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sweatersjCheckBox.setText("Sweaters");
        add(sweatersjCheckBox);
        sweatersjCheckBox.setBounds(1000, 350, 160, 31);

        shoesjCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shoesjCheckBox.setText("Shoes");
        add(shoesjCheckBox);
        shoesjCheckBox.setBounds(1000, 390, 140, 31);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Donate Money:");
        add(jLabel9);
        jLabel9.setBounds(1196, 240, 170, 22);

        jCheckBox50.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox50.setText("$50");
        add(jCheckBox50);
        jCheckBox50.setBounds(1199, 270, 130, 31);

        jCheckBox75.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox75.setText("$75");
        add(jCheckBox75);
        jCheckBox75.setBounds(1299, 270, 130, 31);

        jCheckBox100.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox100.setText("$100");
        add(jCheckBox100);
        jCheckBox100.setBounds(1197, 310, 140, 31);

        jCheckBox200.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox200.setText("$200");
        add(jCheckBox200);
        jCheckBox200.setBounds(1297, 310, 140, 31);

        jCheckBox500.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox500.setText("$500");
        add(jCheckBox500);
        jCheckBox500.setBounds(1197, 360, 140, 31);

        jCheckBox1000.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1000.setText("$1000");
        add(jCheckBox1000);
        jCheckBox1000.setBounds(1303, 360, 140, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cause:");
        add(jLabel10);
        jLabel10.setBounds(750, 470, 120, 22);

        txtCause.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(txtCause);
        txtCause.setBounds(812, 470, 630, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Make Donations:");
        add(jLabel11);
        jLabel11.setBounds(503, 202, 200, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Quantity:");
        add(jLabel12);
        jLabel12.setBounds(1002, 440, 130, 22);

        txtQuantityCloth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQuantityCloth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityClothKeyPressed(evt);
            }
        });
        add(txtQuantityCloth);
        txtQuantityCloth.setBounds(1090, 440, 120, 28);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel13.setText("jLabel2");
        add(jLabel13);
        jLabel13.setBounds(0, 550, 600, 450);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel14.setText("jLabel2");
        add(jLabel14);
        jLabel14.setBounds(600, 550, 600, 450);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Volunteer/volunteerImage.JPG"))); // NOI18N
        jLabel15.setText("jLabel2");
        add(jLabel15);
        jLabel15.setBounds(1190, 550, 770, 450);

        labelVolunteer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add(labelVolunteer1);
        labelVolunteer1.setBounds(920, 76, 180, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        userProcessContainer.add("DonorWorkAreaJPanel", new DonorWorkAreaJPanel(userProcessContainer, account, organization));
//        layout.next(userProcessContainer);

        BloodType bt = (BloodType) bloodGroupComboBox.getSelectedItem();
        double quantity = (double) quantityComboBox.getSelectedItem();
       
       // txtBlood.setText(quantityComboBox.getSelectedItem().toString());
        BloodDonations bd = new BloodDonations(bt);
        bd.setQuantity(quantity);
        bd.setCause(txtCause.getText());
        bd.setDonationType("Blood");
        System.out.println("  ****  "+account.getEmployee());
        account.getEmployee().getMydonations().add(bd);
        JOptionPane.showMessageDialog(this, "Thank you for your donation");

    }//GEN-LAST:event_btnBloodActionPerformed

    private void btnClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        userProcessContainer.add("DonateClothesWorkAreaJPanel", new DonateClothesWorkAreaJPanel(userProcessContainer, account, organization));
//        layout.next(userProcessContainer);

        if (clothesjCheckBox.isSelected() || comfortersjCheckBox.isSelected() || sweatersjCheckBox.isSelected() || shoesjCheckBox.isSelected()) {

            JOptionPane.showMessageDialog(this, "Thank you for your donation");

        }
        ClothDonations cd = new ClothDonations();
        cd.setDonationType("Clothes");
        cd.setQuantity(Double.parseDouble(txtQuantityCloth.getText()));
        cd.setCause(txtCause.getText());
        account.getEmployee().getMydonations().add(cd);
    }//GEN-LAST:event_btnClothesActionPerformed

    private void btnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        userProcessContainer.add("FundRaiserWorkAreaJPanel", new FundRaiserWorkAreaJPanel(userProcessContainer, account, organization));
//        layout.next(userProcessContainer);
            CashDonations cd = new CashDonations();
            if (jCheckBox50.isSelected() || jCheckBox75.isSelected() || jCheckBox75.isSelected() || jCheckBox100.isSelected() || jCheckBox500.isSelected() || jCheckBox200.isSelected() || jCheckBox500.isSelected() || jCheckBox1000.isSelected()) {

            JOptionPane.showMessageDialog(this, "Thank you for your donation");
            if (jCheckBox100.isSelected()) {
               // txtMoney.setText("100");
                cd.setQuantity(100);
            } else if (jCheckBox1000.isSelected()) {
                //txtMoney.setText("1000");
                cd.setQuantity(1000);
            } else if (jCheckBox50.isSelected()) {
                //txtMoney.setText("50");
                cd.setQuantity(50);
            } else if (jCheckBox75.isSelected()) {
                //txtMoney.setText("75");
                cd.setQuantity(75);
            } else if (jCheckBox200.isSelected()) {
                //txtMoney.setText("200");
                cd.setQuantity(200);
            } else if (jCheckBox500.isSelected()) {
                //txtMoney.setText("500");
                cd.setQuantity(500);
            }
        }
        cd.setCause(txtCause.getText());
        cd.setDonationType("Money");
        account.getEmployee().getMydonations().add(cd);
    }//GEN-LAST:event_btnMoneyActionPerformed

    private void txtQuantityClothKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityClothKeyPressed
        // TODO add your handling code here:
        
        Validator.onlyInteger(evt, txtQuantityCloth);
    }//GEN-LAST:event_txtQuantityClothKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bloodGroupComboBox;
    private javax.swing.JButton btnBlood;
    private javax.swing.JButton btnClothes;
    private javax.swing.JButton btnMoney;
    private javax.swing.JCheckBox clothesjCheckBox;
    private javax.swing.JCheckBox comfortersjCheckBox;
    private javax.swing.JCheckBox jCheckBox100;
    private javax.swing.JCheckBox jCheckBox1000;
    private javax.swing.JCheckBox jCheckBox200;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox500;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelVolunteer;
    private javax.swing.JLabel labelVolunteer1;
    private javax.swing.JComboBox quantityComboBox;
    private javax.swing.JCheckBox shoesjCheckBox;
    private javax.swing.JCheckBox sweatersjCheckBox;
    private javax.swing.JTextField txtCause;
    private javax.swing.JTextField txtQuantityCloth;
    // End of variables declaration//GEN-END:variables
}
