/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer.FundRaiser;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MoneyContributionWorkRequest;
import UserInterface.Volunteer.Volunteer.VolunteerWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class FundRaiserWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FundRaiserWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organiaztion;
    public FundRaiserWorkAreaJPanel(JPanel userProcessContainer, UserAccount account,Organization organization) {
        initComponents();
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        this.organiaztion = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox200 = new javax.swing.JCheckBox();
        jCheckBox500 = new javax.swing.JCheckBox();
        jCheckBox1000 = new javax.swing.JCheckBox();
        donateMoneyjButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Donate Money");

        jLabel2.setText("Select amount to donate:");

        jCheckBox50.setText("$50");

        jCheckBox75.setText("$75");

        jCheckBox100.setText("$100");

        jCheckBox200.setText("$200");

        jCheckBox500.setText("$500");

        jCheckBox1000.setText("$1000");

        donateMoneyjButton.setText("Donate ");
        donateMoneyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateMoneyjButtonActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(jCheckBox1000)
                            .addComponent(jCheckBox500)
                            .addComponent(jCheckBox200)
                            .addComponent(jCheckBox100)
                            .addComponent(jCheckBox75)
                            .addComponent(jCheckBox50)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(donateMoneyjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox50)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox75)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox100)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox200)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox500)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1000)
                .addGap(25, 25, 25)
                .addComponent(donateMoneyjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donateMoneyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateMoneyjButtonActionPerformed
        // TODO add your handling code here:
        if(jCheckBox50.isSelected()||jCheckBox75.isSelected()||jCheckBox75.isSelected()||jCheckBox100.isSelected()||jCheckBox500.isSelected()||jCheckBox200.isSelected()||jCheckBox500.isSelected()||jCheckBox1000.isSelected()){
            
            MoneyContributionWorkRequest mcwr = new MoneyContributionWorkRequest();
            if(jCheckBox100.isSelected()){
            mcwr.setAmount(100);
            }else if (jCheckBox1000.isSelected()){
            mcwr.setAmount(1000);
            }else if(jCheckBox50.isSelected()){
            mcwr.setAmount(50);
            }else if (jCheckBox75.isSelected()){
            mcwr.setAmount(75);
            }else if (jCheckBox200.isSelected()){
            mcwr.setAmount(200);
            }else if(jCheckBox500.isSelected()){
            mcwr.setAmount(500);
            }
                         
//            userAccount.getWorkQueue().getWorkRequestList().add(mcwr);
//            organiaztion.getWorkQueue().getWorkRequestList().add(mcwr);
            JOptionPane.showMessageDialog(this, "Thanks for your valuable contribution..");
        }
    }//GEN-LAST:event_donateMoneyjButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerWorkAreaJPanel vwjp = (VolunteerWorkAreaJPanel) component;
        //vwjp.totalMoney();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton donateMoneyjButton;
    private javax.swing.JCheckBox jCheckBox100;
    private javax.swing.JCheckBox jCheckBox1000;
    private javax.swing.JCheckBox jCheckBox200;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox500;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
