/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Volunteer.Donor;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.Volunteer.Volunteer.VolunteerWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class DonateClothesWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonateClothesWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    public DonateClothesWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,Organization organization) {
        initComponents();
        this.userProcessContainer =userProcessContainer;
        this.organization = organization;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clothesjCheckBox = new javax.swing.JCheckBox();
        comfortersjCheckBox = new javax.swing.JCheckBox();
        sweatersjCheckBox = new javax.swing.JCheckBox();
        shoesjCheckBox = new javax.swing.JCheckBox();
        donateBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Donate Clothes");

        jLabel2.setText("Select from below to donate:");

        clothesjCheckBox.setText("Clothes");

        comfortersjCheckBox.setText("Comforters");

        sweatersjCheckBox.setText("Sweaters");

        shoesjCheckBox.setText("Shoes");

        donateBtn.setText("Donate");
        donateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateBtnActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(shoesjCheckBox)
                        .addComponent(sweatersjCheckBox)
                        .addComponent(comfortersjCheckBox)
                        .addComponent(clothesjCheckBox)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(donateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(clothesjCheckBox)
                .addGap(18, 18, 18)
                .addComponent(comfortersjCheckBox)
                .addGap(18, 18, 18)
                .addComponent(sweatersjCheckBox)
                .addGap(18, 18, 18)
                .addComponent(shoesjCheckBox)
                .addGap(18, 18, 18)
                .addComponent(donateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateBtnActionPerformed
        // TODO add your handling code here:
        if(clothesjCheckBox.isSelected()|| comfortersjCheckBox.isSelected()||sweatersjCheckBox.isSelected()||shoesjCheckBox.isSelected()){
         
            JOptionPane.showMessageDialog(this, "Thanks for donating..");
        }
    }//GEN-LAST:event_donateBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerWorkAreaJPanel vwjp = (VolunteerWorkAreaJPanel) component;
        //nwjp.patientComboBox();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox clothesjCheckBox;
    private javax.swing.JCheckBox comfortersjCheckBox;
    private javax.swing.JButton donateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox shoesjCheckBox;
    private javax.swing.JCheckBox sweatersjCheckBox;
    // End of variables declaration//GEN-END:variables
}
