/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Rescue;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.RescueAdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vishnu
 */
public class RescueAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RescueAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account; 
    RescueAdminOrganization organization; 
    Enterprise enterprise; 
    EcoSystem business;
    public RescueAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, RescueAdminOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account=account;
        this.business=business;
        this.organization= organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelEnterprise = new javax.swing.JLabel();
        manageEmployeejButton = new javax.swing.JButton();
        manageUserjButton = new javax.swing.JButton();
        manageOrganisationjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rescue Admin Work Area");
        add(jLabel1);
        jLabel1.setBounds(700, 80, 611, 60);

        labelEnterprise.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        add(labelEnterprise);
        labelEnterprise.setBounds(960, 340, 230, 40);

        manageEmployeejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageEmployeejButton.setText("Manage Employee");
        manageEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeejButtonActionPerformed(evt);
            }
        });
        add(manageEmployeejButton);
        manageEmployeejButton.setBounds(940, 490, 240, 31);

        manageUserjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageUserjButton.setText("Manage User Account");
        manageUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserjButtonActionPerformed(evt);
            }
        });
        add(manageUserjButton);
        manageUserjButton.setBounds(940, 560, 240, 31);

        manageOrganisationjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageOrganisationjButton.setText("Manage Organisation");
        manageOrganisationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganisationjButtonActionPerformed(evt);
            }
        });
        add(manageOrganisationjButton);
        manageOrganisationjButton.setBounds(940, 420, 240, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Rescue/rescueImage.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1950, 1000);
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganisationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganisationjButtonActionPerformed
        // TODO add your handling code here:
        RescueManageOrganisationJPanel manageOrganizationJPanel = new RescueManageOrganisationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("RescueManageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganisationjButtonActionPerformed

    private void manageEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeejButtonActionPerformed
        // TODO add your handling code here:
        RescueManageEmployeeJPanel manageEmployeeJPanel = new RescueManageEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("RescueManageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeejButtonActionPerformed

    private void manageUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserjButtonActionPerformed
        // TODO add your handling code here:
        RescueManageUserAccountJPanel muajp = new RescueManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("RescueManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelEnterprise;
    private javax.swing.JButton manageEmployeejButton;
    private javax.swing.JButton manageOrganisationjButton;
    private javax.swing.JButton manageUserjButton;
    // End of variables declaration//GEN-END:variables
}
