/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Medical.Doctor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
//import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AssignWorkRequest;
import Business.WorkQueue.PatientStatusWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import utility.Validator;

/**
 *
 * @author Vishnu
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private PatientStatusWorkRequest pswr;
    
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = (DoctorOrganization) organization;
        this.enterprise = enterprise;
        this.business = business;
        labelDoctor.setText(userAccount.getEmployee().getName());
        patientComboBox();
        populateTable();
    }
    
    public void patientComboBox(){
        patientjComboBox.removeAllItems();
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkRequestList()){
            if (wr instanceof AssignWorkRequest){
                patientjComboBox.addItem(((AssignWorkRequest) wr).getPatient());
            }
        }
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) patientStatusjTable.getModel();

        model.setRowCount(0);
        
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            
            Object[] row = new Object[3];
            row[0] = request;
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
      
            model.addRow(row);
            
        }
    }
  
    public void patientDetails() {
           Patient p = (Patient) patientjComboBox.getSelectedItem();
            txtName.setText(p.getName());
            txtAge.setText(String.valueOf(p.getAge()));
            txtEmail.setText(p.getEmail());
            txtGender.setText(String.valueOf(p.getGender()));
            txtMobile.setText(String.valueOf(p.getMobileNo()));

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientjComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BPjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        temperaturejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        weightjTextField = new javax.swing.JTextField();
        healthjProgressBar = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        patientReportjButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        healthIndexjTextField = new javax.swing.JTextField();
        dischargejButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientStatusjTable = new javax.swing.JTable();
        checkReportjButton = new javax.swing.JButton();
        labelDoctor = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        injuryjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DoctorWorkArea");
        add(jLabel1);
        jLabel1.setBounds(80, 100, 152, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Doctor:");
        add(jLabel2);
        jLabel2.setBounds(80, 180, 76, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Patient:");
        add(jLabel3);
        jLabel3.setBounds(80, 220, 76, 22);

        patientjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientjComboBoxActionPerformed(evt);
            }
        });
        add(patientjComboBox);
        patientjComboBox.setBounds(180, 220, 145, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Patient Report:");
        add(jLabel4);
        jLabel4.setBounds(550, 80, 138, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Blood Pressure:");
        add(jLabel5);
        jLabel5.setBounds(690, 330, 142, 30);

        BPjTextField.setEditable(false);
        add(BPjTextField);
        BPjTextField.setBounds(860, 320, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Temperatue:");
        add(jLabel6);
        jLabel6.setBounds(710, 380, 117, 30);

        temperaturejTextField.setEditable(false);
        add(temperaturejTextField);
        temperaturejTextField.setBounds(860, 380, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Weight:");
        add(jLabel7);
        jLabel7.setBounds(750, 440, 72, 30);

        weightjTextField.setEditable(false);
        add(weightjTextField);
        weightjTextField.setBounds(860, 440, 140, 40);

        healthjProgressBar.setStringPainted(true);
        add(healthjProgressBar);
        healthjProgressBar.setBounds(860, 560, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Progress:");
        add(jLabel9);
        jLabel9.setBounds(730, 560, 86, 30);

        patientReportjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientReportjButton.setText("Request Patient Report");
        patientReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientReportjButtonActionPerformed(evt);
            }
        });
        add(patientReportjButton);
        patientReportjButton.setBounds(540, 230, 270, 60);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Health index:");
        add(jLabel11);
        jLabel11.setBounds(700, 620, 122, 30);

        healthIndexjTextField.setEditable(false);
        add(healthIndexjTextField);
        healthIndexjTextField.setBounds(860, 610, 140, 40);

        dischargejButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dischargejButton.setText("Discharge");
        dischargejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dischargejButtonActionPerformed(evt);
            }
        });
        add(dischargejButton);
        dischargejButton.setBounds(120, 590, 159, 43);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Patient Details:");
        add(jLabel10);
        jLabel10.setBounds(80, 300, 139, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Name:");
        add(jLabel13);
        jLabel13.setBounds(80, 360, 60, 22);

        txtName.setEditable(false);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(160, 360, 159, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Age:");
        add(jLabel14);
        jLabel14.setBounds(80, 400, 41, 22);

        txtAge.setEditable(false);
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });
        add(txtAge);
        txtAge.setBounds(160, 400, 159, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Email:");
        add(jLabel15);
        jLabel15.setBounds(80, 440, 56, 22);

        txtEmail.setEditable(false);
        add(txtEmail);
        txtEmail.setBounds(160, 440, 159, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Mobile:");
        add(jLabel16);
        jLabel16.setBounds(80, 480, 66, 22);

        txtMobile.setEditable(false);
        add(txtMobile);
        txtMobile.setBounds(160, 480, 158, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Gender:");
        add(jLabel17);
        jLabel17.setBounds(80, 520, 73, 22);

        patientStatusjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Doctor", "Nurse", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientStatusjTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(540, 130, 400, 80);

        checkReportjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkReportjButton.setText("Check Report");
        checkReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReportjButtonActionPerformed(evt);
            }
        });
        add(checkReportjButton);
        checkReportjButton.setBounds(820, 230, 178, 60);

        labelDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDoctor.setText("doctorName");
        add(labelDoctor);
        labelDoctor.setBounds(180, 180, 120, 22);

        txtGender.setEditable(false);
        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGenderKeyPressed(evt);
            }
        });
        add(txtGender);
        txtGender.setBounds(160, 520, 159, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Injuries:");
        add(jLabel8);
        jLabel8.setBounds(740, 500, 80, 30);

        injuryjTextField.setEditable(false);
        add(injuryjTextField);
        injuryjTextField.setBounds(860, 500, 140, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Medical/Doctor/Wimage.jpeg"))); // NOI18N
        jLabel12.setText("jLabel12");
        add(jLabel12);
        jLabel12.setBounds(350, 130, 1600, 728);
    }// </editor-fold>//GEN-END:initComponents

    private void patientReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientReportjButtonActionPerformed
        // TODO add your handling code here:
        PatientStatusWorkRequest pswr = new PatientStatusWorkRequest();
        pswr.setSender(userAccount);
        
        pswr.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NurseOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(pswr);
            userAccount.getWorkQueue().getWorkRequestList().add(pswr);
        }
        populateTable();
    }//GEN-LAST:event_patientReportjButtonActionPerformed

    private void checkReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReportjButtonActionPerformed
            // TODO add your handling code here:
            
        int selectedRow = patientStatusjTable.getSelectedRow();

            if (selectedRow >= 0) {
            PatientStatusWorkRequest  pswr= (PatientStatusWorkRequest) patientStatusjTable.getValueAt(selectedRow, 0);
            BPjTextField.setText(String.valueOf(pswr.getBloodPressure()));
            temperaturejTextField.setText(String.valueOf(pswr.getTemperature()));
            weightjTextField.setText(String.valueOf(pswr.getWeight()));
            injuryjTextField.setText(pswr.getInjury());
            
            Random rand = new Random();
            int value1 = rand.nextInt(50-25)+25;
            int value2 = rand.nextInt(100-50)+50;
                if (pswr.getBloodPressure() <= 100 && pswr.getTemperature() <= 98 && pswr.getWeight() <= 90) {
                    healthIndexjTextField.setText("Stable");
                    healthjProgressBar.setValue(value2);
                } else {
                    healthIndexjTextField.setText("Weak");
                    healthjProgressBar.setValue(value1);
                }
        }
    }//GEN-LAST:event_checkReportjButtonActionPerformed

    private void dischargejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dischargejButtonActionPerformed
        // TODO add your handling code here:
        if (healthIndexjTextField.getText().equalsIgnoreCase("stable")){
            JOptionPane.showMessageDialog(this,"Patient discharged successfully");
        }else{
            JOptionPane.showMessageDialog(this,"Patient needs further attention!!");
        }
    }//GEN-LAST:event_dischargejButtonActionPerformed

    private void patientjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientjComboBoxActionPerformed
        // TODO add your handling code here:
        patientDetails();
        
    }//GEN-LAST:event_patientjComboBoxActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtName);
        
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        Validator.onlyInteger(evt, txtAge);
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtGenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyPressed
        // TODO add your handling code here:
        Validator.onlyString(evt, txtGender);
    }//GEN-LAST:event_txtGenderKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPjTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkReportjButton;
    private javax.swing.JButton dischargejButton;
    private javax.swing.JTextField healthIndexjTextField;
    private javax.swing.JProgressBar healthjProgressBar;
    private javax.swing.JTextField injuryjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDoctor;
    private javax.swing.JButton patientReportjButton;
    private javax.swing.JTable patientStatusjTable;
    private javax.swing.JComboBox patientjComboBox;
    private javax.swing.JTextField temperaturejTextField;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField weightjTextField;
    // End of variables declaration//GEN-END:variables
}
